# Generated by Django 4.2.30 on 2026-05-03 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address (e.g. AA:BB:CC:DD:EE:FF)', regex='^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$')]),
        ),
    ]
