# Generated by Django 4.2.30 on 2026-05-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_device_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
